version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: lawnsensei.Server/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: lawnsensei.client/Dockerfile
    ports:
      - "3000:80"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "gh3x9t14yAvTZU"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
